apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deakin-task-board-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deakin-task-board
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50 