apiVersion: v1
kind: Service
metadata:
  name: deakin-task-board-service
spec:
  type: LoadBalancer
  selector:
    app: deakin-task-board
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080